docs_dir: .
site_dir: ../site
site_name: shtab documentation
site_url: https://docs.iterative.ai/shtab/
site_author: Iterative
repo_name: iterative/shtab
repo_url: https://github.com/iterative/shtab
copyright: Copyright &copy; 2021 Casper da Costa-Luis

theme:
  name: material
  logo: https://github.com/iterative/shtab/raw/master/meta/logo.png
  favicon: https://github.com/iterative/shtab/raw/master/meta/logo.png
  palette:
  - scheme: default
    primary: white
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    primary: orange
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
plugins:
- search
- minify:
    minify_js: true
    minify_html: true
markdown_extensions:
- admonition
- toc:
    permalink: '#'
- pymdownx.superfences
- pymdownx.tabbed
